branches/urls.py
from django.urls import path
from branches import views

app_name = 'branches'

urlpatterns = [
    path('', views.BranchHomeView.as_view(), name='branch_home'),
    path('create_branch/', views.CreateBranchView.as_view(), name='create_branch'),
    path('update_branch/<int:pk>/', views.UpdateBranchView.as_view(), name='update_branch'),
    path('delete_branch/<int:pk>/', views.DeleteBranchView.as_view(), name='delete_branch'),
]

pos_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('staff/', include('staff.urls')),
    path('supplier/', include('supplier.urls')),
    path('branch/', include('branches.urls')),
    path('products/', include('products.urls')),
    path('deliveries/', include('deliveries.urls')),
    path('customers/', include('customers.urls')),
    path('sales/', include('sales.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductHomeView.as_view(), name='product_home'),
    path('create_product/', views.CreateProductView.as_view(), name='create_product'),
    path('product_detail/<int:pk>/', views.ProductDetailView.as_view(), name='detail_product'),
    path('update_product/<int:pk>/', views.ProductUpdateView.as_view(), name='update_product'),
    path('delete_product/<int:pk>/', views.ProductDeleteView.as_view(), name='delete_product'),
    path('add_transfer/', views.ProductAddTransfer.as_view(), name='add_transfer'),
    path('transfer_product/', views.TransferProduct.as_view(), name='transfer_product'),
    path('set_transfer_to/', views.SetTransferTO.as_view(), name='set_transfer_to'),
    path('delete_cart_product/<int:product_id>/', views.DeleteCartProduct.as_view(), name='delete_cart_product'),
    path('clear_list/', views.ClearList.as_view(), name='clear_list'),
]

sales/urls.py
from django.urls import path
from sales import views

app_name = 'sales'

urlpatterns = [
    
]

products/forms.py
from django import forms
from products.models import Products
from branches.models import Branch

class CreateProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['sku_code'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'rows': 1})
        self.fields['manufacturer'].widget.attrs.update({'class': 'form-control'})
        self.fields['supplier'].widget.attrs.update({'class': 'form-control'})
        self.fields['product_image'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Products
        exclude = ['created','updated', 'quantity', 'buying_price', 'wholesale_price', 'retail_price']

class UpdateProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control'})
        self.fields['sku_code'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})
        self.fields['description'].widget.attrs.update({'rows': 1})
        self.fields['manufacturer'].widget.attrs.update({'class': 'form-control'})
        self.fields['supplier'].widget.attrs.update({'class': 'form-control'})
        self.fields['quantity'].widget.attrs.update({'class': 'form-control'})
        self.fields['buying_price'].widget.attrs.update({'class': 'form-control'})
        self.fields['retail_price'].widget.attrs.update({'class': 'form-control'})
        self.fields['wholesale_price'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Products
        exclude = ['created', 'updated',]

class TransferFiltersForm(forms.Form):
    date_from = forms.DateTimeField()
    date_to = forms.DateTimeField()
    transfered_from = forms.ModelChoiceField(queryset=Branch.objects.all())
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['date_from'].widget.attrs.update({'class': 'form-control'})
        self.fields['date_from'].widget.attrs.update({'id': 'date_from'})
        self.fields['date_from'].widget.attrs.update({'placeholder': 'Date from'})
        self.fields['date_to'].widget.attrs.update({'class': 'form-control'})
        self.fields['date_to'].widget.attrs.update({'id': 'date_to'})
        self.fields['date_to'].widget.attrs.update({'placeholder': 'Date to'})
        self.fields['transfered_from'].widget.attrs.update({'class': 'form-control'})

class SetTransferToForm(forms.Form):
    transfer_to = forms.ModelChoiceField(queryset=Branch.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['transfer_to'].widget.attrs.update({'class': 'form-control'})


class ProductTransferForm(forms.Form):
    product = forms.CharField(max_length=100)
    quantity = forms.IntegerField()
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['product'].widget.attrs.update({'class': 'form-control'})
        self.fields['product'].widget.attrs.update({'id': 'product_id'})
        self.fields['quantity'].widget.attrs.update({'class': 'form-control'})
    

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from datetime import datetime
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import TemplateView, FormView, CreateView, UpdateView, DeleteView, DetailView, ListView
from products.models import Products, Transfer, TransferProduct, BranchProduct
from products.forms import CreateProductForm, UpdateProductForm, TransferFiltersForm, SetTransferToForm, ProductTransferForm
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from deliveries.models import Delivery, Stock

# Create your views here.

class ProductHomeView(PermissionRequiredMixin, TemplateView):
    permission_denied_message = "you do not have permission to view products"
    permission_required = ['products.view_product']
    raise_exception = True
    template_name = "products/product_home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["products"] = Products.objects.all().order_by('-pk')
        return context
    

class CreateProductView(PermissionRequiredMixin, CreateView):
    permission_denied_message = 'You do not have permissions to add products'
    permission_required = ['products.add_product']
    raise_exception = True
    form_class = CreateProductForm
    model = Products
    template_name = "products/create_product.html"

    def get(self, request, *args, **kwargs):
        products = Products.objects.all().order_by('-pk')[:25]
        context = {
            'products': products,
            'form': self.form_class
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Product is created successfully', extra_tags='alert alert-success')
            return redirect('products:create_product')
        else:
            messages.error(request, 'Product is not added', extra_tags='alert alert-danger')
            return redirect('products:create_product')


class ProductDetailView(DetailView):
    permission_denied_message ='You do not have permission to view the product'
    permission_required = ['products.view_product']
    raise_exception =True
    model = Products
    template_name = "products/product_detail.html"
    context_object_name = 'product'
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = context['product']
        
    

        branch_stock,created = BranchProduct.objects.get_or_create(
            branch_id = self.request.user.branch_id,
            product_id = product.pk, 
            
        )
        try:
            stock = Stock.objects.filter(
                product_id = product.pk,
                current_branch_id = self.request.user.branch_id,
                home_branch_id = self.request.user.branch_id
            ).latest('posted')
            buying_price = Stock.buying_price
            retail_price = Stock.retail_price
            wholesale_price = Stock.wholesale_price
            supplier = Stock.delivery.received_from.name

        except ObjectDoesNotExist:
            buying_price = 0.00
            retail_price = 0.00
            wholesale_price = 0.00
            supplier = product.supplier.name
        
        context['Stock_Vals'] = {
            'cost_value': buying_price*branch_stock.quantity,
            'retail_value': retail_price*branch_stock.quantity,
            'retail_price': retail_price,
            'wholesale_value': wholesale_price*branch_stock.quantity,
            'wholesale_price': wholesale_price,
            'quantity': branch_stock.quantity,
            'buying_price': buying_price,
            'supplier': supplier,
        }

        return context


class ProductUpdateView(PermissionRequiredMixin, UpdateView):
    permission_denied_message = "you do not have permission to change product"
    permission_required = ['products.change_product']
    raise_exception = True
    model = Products
    template_name = "products/update_product.html"
    form_class = UpdateProductForm
    success_url = 'products:update_product'
    context_object_name = 'product'

    def get_success_url(self):
        messages.success(self.request, "Product is Updated successfully", extra_tags='alert alert-success')
        return reverse_lazy('products:update_product', kwargs={'pk': self.kwargs['pk']})


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    permission_denied_message = 'you do not have permission to delete product'
    permission_required = ['products.delete_product']
    raise_exception = True
    model = Products
    template_name = "products/product_confirm_delete.html"
    success_url = reverse_lazy('products:product_home')


class ProductAddTransfer(PermissionRequiredMixin, FormView):
    permission_denied_message = "you do not have permission to add product"
    permission_required = ['transfer.add_transfer']
    raise_exception = True
    form_class = ProductTransferForm
    template_name = 'products/product_add_transfer.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        
        if form.is_valid():
            product = get_object_or_404(Products, pk=form.cleaned_data['product'])
            
            try:
                stock = Stock.objects.filter(
                    product_id = product.pk,
                    current_branch_id = request.user.branch_id,
                    home_branch_id = request.user.branch_id
                ).latest('posted')

            except ObjectDoesNotExist:
                messages.error(request, 'Out of Stock, No purchase on record', extra_tags='alert alert-warning')
                return redirect('products:transfer_product')

            if stock.quantity < form.cleaned_data['quantity']:
                messages.error(request, f"Out of range. only {stock.quantity} available", extra_tags='alert alert-warning')
                return redirect('products:transfer_product')

            new_product = {
                'product_name' : product.name,
                'product_id' : product.pk,
                'unit_cost' : stock.buying_price,
                'quantity' : form.cleaned_data['quantity'],
                'total': form.cleaned_data['quantity'] * stock.buying_price,
            }

            if "products" not in request.session:
                request.session['products'] = list()
                request.session['products'].append(new_product)
                request.session['products_total'] = new_product['total']

            else:
                cart_products = request.session['products']
                product_id = [pk['product_id'] for pk in cart_products]

                if new_product['product_id'] not in product_id:
                    cart_products.append(new_product)
                else:
                    for item in cart_products:
                        if item['product_id'] == new_product['product_id']:
                            item['quantity'] = item['quantity'] + new_product['quantity']
                            item['total'] = item['quantity'] * item['unit_cost']

                request.session['products'] = cart_products
                request.session['products_total'] = sum(item['total'] for item in cart_products)

        return redirect('products:product_home')

class TransferProduct(PermissionRequiredMixin, FormView):
    permission_denied_message = "you do not have permission to add product"
    permission_required = ['transfer.add_transfer']
    raise_exception = True
    form_class = ProductTransferForm
    template_name = 'products/product_add_transfer.html'

    def get(self, request, *args, **kwargs):
        if 'transfer_to_id' not in self.request.session.keys():
            return redirect('products:set_transfer_to')

        else:
            return render(request, self.template_name, context=self.get_context_data())


class SetTransferTO(PermissionRequiredMixin, FormView):
    permission_denied_message = "you do not have permission  set transfer to product"
    permission_required = ['transfer.add_transfer']
    raise_exception = True
    form_class = SetTransferToForm
    template_name = 'products/set_transfer_to.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)

        if form.is_valid():
            if form.cleaned_data['transfer_to'].pk == request.user.branch_id:
                messages.error(request, "Can not Transfer to same branch", extra_tags='alert alert-info')
                return redirect('products:set_transfer_to')
            request.session['transfer_to'] = form.cleaned_data['transfer_to'].name
            request.session['transfer_to_id'] = form.cleaned_data['transfer_to'].pk
            return redirect('products:add_transfer')

        else:
            return render(request, self.template_name, context=self.get_context_data())

class DeleteCartProduct(PermissionRequiredMixin, TemplateView):
    permission_denied_message = "you do not have permission  to add transfer"
    permission_required = ['transfer.add_transfer']
    raise_exception = True

    def get(self, request, *args, **kwargs):
        if not kwargs['product_id']:
            return redirect('products:transfer_product')

        if 'products' in request.session.keys():
            if self.kwargs['product_id'] in [p['product_id'] for p in request.session['products']]:
                cart_products = request.session['products']
                for product in cart_products:
                    if product['product_id'] == self.kwargs['product_id']:
                        cart_products.remove(product)
                        request.session['products'] = cart_products

templates/products/create_product.html
{% extends 'dashboard/dashboard_base.html' %}
{% load crispy_forms_tags %}


{% block dashboard_content %}
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h4>Add Product</h4>
            </div>
            <div class="card-body">
                <form action="{% url 'products:create_product' %}" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary btn-block">Add Product</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-8">
        <div class="card">
            <div class="card-header">
                <h4>25 Recent Products</h4>
            </div>
            <div class="card-body">
                
                {% if products|length > 0 %}
                <table class="table table-striped table-inverse table-responsive">
                    <thead class="thead-inverse">
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Sku Code</th>
                            <th>Manufacturer</th>
                            <th>Supplier</th>
                            <th>Description</th>
                        </tr>
                        </thead>
                        <tbody>
                            
                            {% for product in products %}
                            <tr>
                                <td scope="row">{{ forloop.counter }}</td>
                                <td scope="col">{{ product.name }}</td>
                                <td>{{ product.sku_code }}</td>
                                <td>{{ product.manufacturer }}</td>
                                <td>{{ product.supplier }}</td>
                                <td> {{ product.description }}</td>
                            </tr>
                            {% endfor %}
                                
                           
                        </tbody>
                </table>
                {% else %}
                <div class="alert alert-info">No Branch have been added yet</div>
                {% endif %}
                    
            </div>
        </div>
    </div>
{% endblock dashboard_content %}
    

templates/products/product_add_transfer.html
{% extends 'dashboard/dashboard_base.html' %}
{% load crispy_forms_tags %}


{% block dashboard_content %}
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                <h4>Prdouct Add Transfer</h4>
            </div>
            <div class="card-body">
                <form action="{% url 'products:add_transfer' %}" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-success btn-block">Add <i class="fa fa-plus"></i></button>
                        </div>
                        <div class="col">
                            <button type="reset" class="btn btn-primary btn-block">Reset <i class="fa fa-remove"></i></button>
                        </div>
                        
                    </div>
                    <p class="mt-3">
                        <a href="{% url 'products:set_transfer_to' %}" class="btn btn-info btn-block">Change Branch To <i class="fa fa-edit"></i></a>
                    </p>
                </form>
            </div>
        </div>
    </div>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                
                {% if request.session.products|length > 0 %}
                <table class="table table-striped table-resposive table-sm">
                    <thead>
                        <th class="text-center"><i class="fa fa-remove"></i></th>
                        <th scope="row">Item</th>
                        <th scope="row">Quantity</th>
                        <th scope='row'>Unit Cost</th>
                        <th scope="row">Total</th>
                    </thead>
                    <tbody>
                        
                        {% for product in request.session.products %}
                            <tr>
                                <td>
                                    <a href="{% url 'products:delete_cart_product' product_id=product.product_id %}"><i class="fa fa-trash text-danger"></i></a>
                                </td>
                                <td>{{ product.product_name }}</td>
                                <td>{{ product.quantity }}</td>
                                <td>{{ product.unit_cost }}</td>
                                <td>{{ product.total }}</td>
                            </tr>
                        {% endfor %}
                            
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-3">
                        <a href="" class="btn btn-info">Submit <i class="fa fa-send"></i></a>
                    </div>
                    <div class="col-3"></div>
                    <div class="col-3">
                        <a href="{% url 'clear_list' %}" class="btn btn-light">Clear List <i class="fa fa-eraser text-danger"></i></a>
                    </div>
                    <div class="col-3">
                        <a href="" class="btn btn-light">Total {{ request.session.products_total }}</a>
                    </div>
                    
                </div>
                {% else %}
                <div class="alert alert-info">No product in list</div>
                {% endif %}
                    
            </div>
        </div>
    </div>
{% endblock dashboard_content %}
    

templates/products/product_confirm_delete.html
{% extends 'dashboard/dashboard_base.html' %}

{% block dashboard_content %}
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h4>Delete Staff</h4>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <p>Are you Sure to Delete This {{ object.name }}</p>
                <input type="submit" value="confirm" class="btn btn-warning btn-sm">
            </form>
        </div>
    </div>
</div>
    
{% endblock dashboard_content %}

templates/products/product_detail.html
{% extends 'dashboard/dashboard_base.html' %}


{% block dashboard_content %}
    <div class="col-4">
        <div class="card">
            
            {% if product.product_image %}
                <img class="card-img-top" src="{{ product.product_image.url }}" alt="image">
            {% endif %}
                
            <div class="card-body bg-dark text-center">
                <h5 class="card-title text-white">{{ product.name }}</h5>
                <hr class="bg-light mt-0">
                <p class="card-text text-white">{{ product.description }}</p>
                <caption>
                    <h5 class="mb-0 p-2">Stock Value</h5>
                </caption>
                <table class="table table-striped  table-responsive bg-light">
                    <thead class="thead-inverse">
                        <tr>
                            <th>Cost</th>
                            <th>Wholesale</th>
                            <th>Retail</th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td scope="row">{{ Stock_Vals.cost_value}}</td>
                                <td>{{ Stock_Vals.wholesale_value}}</td>
                                <td>{{ Stock_Vals.retail_value}}</td>
                            </tr>
                           
                        </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-8">
        <div class="card">
            <div class="card-header">
                <h4>{{ product.name }} Details</h4>
            </div>
            <div class="card-body">
                <table class="table">
                    
                    <tbody>
                        <tr>
                            <td>Qty in Stock</td>
                            <td>{{ Stock_Vals.quantity }} @ {{ request.user.branch.name }}</td>
                        </tr>
                        <tr>
                            <td>Buying Price</td>
                            <td>{{ Stock_Vals.buying_price }}</td>
                        </tr>
                        <tr>
                            <td>Retail Price</td>
                            <td>{{ Stock_Vals.retail_price }}</td>
                        </tr>
                        <tr>
                            <td>Wholesale Price</td>
                            <td>{{ Stock_Vals.wholesale_price }}</td>
                        </tr>
                        <tr>
                            <td>Supplier</td>
                            <td>{{ Stock_Vals.supplier }}</td>
                        </tr>
                        <tr>
                            <td>SKU Code</td>
                            <td>{{ Stock_Vals.sku_code }}</td>
                        </tr>
                        <tr>
                            <td>Manufacturer</td>
                            <td>{{ Stock_Vals.manufacturer }}</td>
                        </tr>
                        <tr>
                            <td>Created</td>
                            <td>{{ Stock_Vals.buying_price }}</td>
                        </tr>
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock dashboard_content %}
    

templates/products/product_home.html
{% extends 'dashboard/dashboard_base.html' %}


{% block dashboard_content %}
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h4>All Products</h4>
        </div>
        <div class="card-body">
            
            {% if products|length > 0 %}
            <table class="table table-striped table-inverse table-responsive">
                <thead class="thead-inverse">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Sku Code</th>
                        <th>Manufacturer</th>
                        <th>Supplier</th>
                        <th>Description</th>
                        <th>View</th>
                        <th>Update</th>
                        <th>Delete</th>
                    </tr>
                    </thead>
                    <tbody>
                        
                        {% for product in products %}
                        <tr>
                            <td scope="row">{{ forloop.counter }}</td>
                            <td scope="col">{{ product.name }}</td>
                            <td>{{ product.sku_code }}</td>
                            <td>{{ product.manufacturer }}</td>
                            <td>{{ product.supplier }}</td>
                            <td> {{ product.description }}</td>
                            <td><a href="{% url 'products:detail_product' pk=product.pk %}" class="btn btn-info btn-sm">View</a></td>
                            <td><a href="{% url 'products:update_product' pk=product.pk %}" class="btn btn-primary btn-sm">Update</a></td>
                            <td><a href="{% url 'products:delete_product' pk=product.pk %}" class='btn btn-danger btn-sm'>Delete</a></td>
                        
                        </tr>
                        {% endfor %}
                            
                       
                    </tbody>
            </table>
            {% else %}
            <div class="alert alert-info">No Product have been added yet</div>
            {% endif %}
                
        </div>
    </div>
</div>
{% endblock dashboard_content %}
    

templates/products/set_transfer_to.html
{% extends 'dashboard/dashboard_base.html' %}
{% load crispy_forms_tags %}


{% block dashboard_content %}
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form action="{% url 'products:set_transfer_to' %}" method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success btn-block">Next</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-body">
                <p>Select the branch to transfer to and click next to start adding products to transfer.
                    To create a new branch,
                </p>
                <a href="{% url 'branches:create_branch' %}" class="text-info">Click Here</a>
            </div>
        </div>
    </div>
{% endblock dashboard_content %}
    

templates/products/update_product.html
{% extends 'dashboard/dashboard_base.html' %}
{% load crispy_forms_tags %}


{% block dashboard_content %}
<div class="col-4">
    <div class="card">
        <div class="card-header">
            <h4>Update Product</h4>
        </div>
        <div class="card-body">
            <form action="{% url 'products:update_product' pk=product.pk %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-block">Update Product</button>
            </form>
        </div>
    </div>
</div>


<div class="col-8">
    <div class="card">
        <div class="card-header">
            <h4>product Details</h4>
        </div>
        <div class="card-body">
            {% if product %}
            <table class="table table-striped table-bordered table-hover table-condensed">
                <tbody>
                    <tr>
                        <td>Name</td>
                        <td>{{ product.name }}</td>
                    </tr>

                    <tr>
                        <td>Description</td>
                        <td>{{ product.description }}</td>
                    </tr>
                    <tr>
                        <td>SKU Code</td>
                        <td>{{ product.sku_code }}</td>
                    </tr>
                    <tr>
                        <td>Supplier</td>
                        <td>{{ product.supplier }}</td>
                    </tr>
                    <tr>
                        <td>Quantity</td>
                        <td>{{ product.quantity }}</td>
                    </tr>
                    <tr>
                        <td>Buying Price</td>
                        <td>{{ product.buying_price }}</td>
                    </tr>
                    <tr>
                        <td>Retail Price</td>
                        <td>{{ product.retail_price }}</td>
                    </tr>
                    <tr>
                        <td>Wholesale Price</td>
                        <td>{{ product.wholesale_price }}</td>
                    </tr>
                    <tr>
                        <td>Date Updated</td>
                        <td>{{ product.updated|date:'d-m-Y H:i' }}</td>
                    </tr>
                </tbody>
            </table>
            {% else %}
            <div class="alert alert-info">No product have been updated yet</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock dashboard_content %}