customers/urls.py
from django.urls import path
from customers import views

app_name = 'customers'

urlpatterns = [
    path('', views.CustomerHomeView.as_view(), name='customer_home'),
    path('add_customer/', views.CustomerCreateView.as_view(), name='create_customer'),
    path('edit_customer/<int:pk>/', views.CustomerUpdateView.as_view(), name='edit_customer'),
    path('detail_customer/<int:pk>/', views.CustomerDetailView.as_view(), name='detail_customer'),
    path('delete_customer/<int:pk>/', views.CustomerDeleteView.as_view(), name='delete_customer'),
    
]

pos_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('staff/', include('staff.urls')),
    path('supplier/', include('supplier.urls')),
    path('branch/', include('branches.urls')),
    path('products/', include('products.urls')),
    path('deliveries/', include('deliveries.urls')),
    path('customers/', include('customers.urls')),
    path('sales/', include('sales.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from sales import views

app_name = 'sales'

urlpatterns = [
    
]

customers/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    """Model definition for Customer."""

    name = models.CharField(max_length=254)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    address = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        """Meta definition for Customer."""

        verbose_name = 'Customer'
        verbose_name_plural = 'Customers'

    def __str__(self):
        """Unicode representation of Customer."""
        return self.name

customers/forms.py
from django import forms
from customers.models import Customer

class CreateCustomerForm(forms.ModelForm):
    """Form definition for Customer."""

    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs.update({'class': 'form-group'})
        self.fields['email'].widget.attrs.update({'class': 'form-group'})
        self.fields['phone'].widget.attrs.update({'class': 'form-group'})
        self.fields['address'].widget.attrs.update({'class': 'form-group'})

    class Meta:
        """Meta definition for Customerform."""

        model = Customer
        exclude = ('created',)

class UpdateCustomerForm(forms.ModelForm):
    """Form definition for Customer."""

    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs.update({'class': 'form-group'})
        self.fields['email'].widget.attrs.update({'class': 'form-group'})
        self.fields['phone'].widget.attrs.update({'class': 'form-group'})
        self.fields['address'].widget.attrs.update({'class': 'form-group'})

    class Meta:
        """Meta definition for Customerform."""

        model = Customer
        exclude = ('created',)

customers/views.py
from django.shortcuts import render,redirect
from customers.models import Customer
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from django.contrib import messages
from customers.forms import CreateCustomerForm, UpdateCustomerForm



# Create your views here.

class CustomerCreateView(PermissionRequiredMixin, CreateView):
    permission_denied_message = 'you do not have permission to add customer'
    permission_required = ['customers.add_customer']
    raise_exception = True
    model = Customer
    template_name = "customers/create_customer.html"
    form_class = CreateCustomerForm

    def get_success_url(self):
        messages.success(self.request, 'Customer have been created successfully', extra_tags='alert alert-success')
        return reverse_lazy('customers:create_customer')


class CustomerHomeView(PermissionRequiredMixin, ListView):
    permission_denied_message = 'you do not have permission to view customer'
    permission_required = ['customers.view_customer']
    raise_exception = True

    model = Customer
    template_name = "customers/customer_home.html"
    context_object_name =  'customers'


class CustomerDetailView(PermissionRequiredMixin, DetailView):
    permission_denied_message = 'you do not have permission to view customer'
    permission_required = ['customers.view_customer']
    raise_exception = True
    model = Customer
    template_name = "customers/customer_detail.html"
    

class CustomerUpdateView(PermissionRequiredMixin, UpdateView):
    permission_denied_message = 'you do not have permission to change customer'
    permission_required = ['customers.change_customer']
    raise_exception = True
    model = Customer
    template_name = "customers/edit_customer.html"
    form_class = UpdateCustomerForm
    
    def get_success_url(self, *args, **kwargs):
        messages.success(self.request, 'Customer have been Updated successfully', extra_tags='alert alert-success')
        return reverse_lazy('customers:edit_customer', kwargs={'pk': self.kwargs['pk']})


class CustomerDeleteView(PermissionRequiredMixin, DeleteView):
    permission_denied_message = 'you do not have permission to delete customer'
    permission_required = ['customers.delete_customer']
    raise_exception = True
    model = Customer
    template_name = "customers/customer_confirm_delete.html"

    def get_success_url(self):
        messages.success(self.request, 'Customer have been Delete successfully', extra_tags='alert alert-success')
        return reverse_lazy('customers:customer_home')

templates/customers/create_customer.html
{% extends 'dashboard/dashboard_base.html' %}
{% load crispy_forms_tags %}

{% block dashboard_content %}
    
<div class="col-4">
    <div class="card">
        <div class="card-header">
            <h4>Add Customer</h4>
        </div>
        <div class="card-body">
            <form action="{% url 'customers:create_customer' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success btn-block">Add Customer</button>
            </form>
        </div>
    </div>
</div>

{% endblock dashboard_content %}
    

templates/customers/customer_confirm_delete.html
{% extends 'dashboard/dashboard_base.html' %}

{% block dashboard_content %}
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h4>Delete Customer</h4>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <p>Are you Sure to Delete This {{ object.name }}</p>
                <input type="submit" value="confirm" class="btn btn-warning btn-sm">
            </form>
        </div>
    </div>
</div>
    
{% endblock dashboard_content %}

templates/customers/customer_detail.html
{% extends 'dashboard/dashboard_base.html' %}


{% block dashboard_content %}
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h4>Customer Details</h4>
        </div>
        <div class="card-body">
            <table class="table table-hover table-striped table-responsive">
                <tbody>
                    <tr>
                        <td>Name</td>
                        <td>{{ customer.name }}</td>
                    </tr>

                    <tr>
                        <td>Phone</td>
                        <td>{{ customer.phone }}</td>
                    </tr>

                    <tr>
                        <td>Email</td>
                        <td>{{ customer.email }}</td>
                    </tr>

                    <tr>
                        <td>Address</td>
                        <td>{{ customer.address }}</td>
                    </tr>
                    <tr>
                        <td>Created</td>
                        <td>{{ customer.created|date:'d-m-Y H:i' }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock dashboard_content %}
    

templates/customers/customer_home.html
{% extends 'dashboard/dashboard_base.html' %}
{% load crispy_forms_tags %}

{% block dashboard_content %}
    
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h4>All Customer</h4>
        </div>
        <div class="card-body">
            
            {% if customers|length > 0 %}
                <table class="table table-striped table-bordered table-hover table-condensed">
                    <thead>
                        <th>#</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Phone</th>
                        <th>Address</th>
                    </thead>
                    <tbody>
                        
                        {% for customer in customers %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ customer.name }}</td>
                                <td>{{ customer.email }}</td>
                                <td>{{ customer.phone }}</td>
                                <td>{{ customer.address }}</td>
                                <td><a href="{% url 'customers:detail_customer' pk=customer.pk %}" class="btn btn-info btn-block">View</a></td>
                                <td><a href="{% url 'customers:edit_customer' pk=customer.pk %}" class="btn btn-success btn-block">Update</a></td>
                                <td><a href="{% url 'customers:delete_customer' pk=customer.pk %}" class="btn btn-danger btn-block">Delete</a></td>
                                

                            </tr>
                        {% endfor %}
                            
                    </tbody>
                </table>
            {% endif %}
                
        </div>
    </div>
</div>

{% endblock dashboard_content %}

templates/customers/edit_customer.html
{% extends 'dashboard/dashboard_base.html' %}
{% load crispy_forms_tags %}

{% block dashboard_content %}
    
<div class="col-4">
    <div class="card">
        <div class="card-header">
            <h4>Update Customer</h4>
        </div>
        <div class="card-body">
            <form action="{% url 'customers:edit_customer' pk=customer.pk %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success btn-block">Update</button>
            </form>
        </div>
    </div>
</div>
<div class="col-8">
    <div class="card">
        <div class="card-header">
            <h4>Customer Details</h4>
        </div>
        <div class="card-body">
            <table class="table table-hover table-striped table-responsive">
                <tbody>
                    <tr>
                        <td>Name</td>
                        <td>{{ customer.name }}</td>
                    </tr>

                    <tr>
                        <td>Phone</td>
                        <td>{{ customer.phone }}</td>
                    </tr>

                    <tr>
                        <td>Email</td>
                        <td>{{ customer.email }}</td>
                    </tr>

                    <tr>
                        <td>Address</td>
                        <td>{{ customer.address }}</td>
                    </tr>
                    <tr>
                        <td>Created</td>
                        <td>{{ customer.created|date:'d-m-Y H:i' }}</td>
                    </tr>
                    <tr>
                        <td>Updated</td>
                        <td>{{ customer.updated|date:'d-m-Y H:i' }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock dashboard_content %}