pos_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('staff/', include('staff.urls')),
    path('supplier/', include('supplier.urls')),
    path('branch/', include('branches.urls')),
    path('products/', include('products.urls')),
    path('deliveries/', include('deliveries.urls')),
    path('customers/', include('customers.urls')),
    path('sales/', include('sales.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from sales import views

app_name = 'sales'

urlpatterns = [
    
]

staff/urls.py
from django.urls import path
from staff import views
app_name='staff'

urlpatterns = [
    path('', views.HomeView.as_view(), name='staff_home'),
    path('set_permissions/<int:pk>/', views.SetPermissions.as_view(), name='set_permission'),
    path('change_branch/<int:pk>/', views.ChangeBranch.as_view(), name='change_branch'),
    path('create_staff/', views.CreateStaff.as_view(), name='create_staff'),
    path('update_staff/<int:pk>', views.StaffUpdate.as_view(), name='update_staff'),
    path('delete_staff/<int:pk>', views.DeleteStaff.as_view(), name='delete_staff'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('update_password/<int:pk>', views.UpdatePassword.as_view(), name='update_password'),
    path('staffpage/', views.StaffPageView.as_view(), name='staffpage'),
]

staff/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from branches.models import Branch
# Create your models here.

class UserManager(BaseUserManager):
    user_in_migration = True
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given Email must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
    
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError("Superuser must have is_staff=True")
        if extra_fields.get('is_superuser') is not True:
            raise ValueError("Superuser must have is_superuser=True")
        return self._create_user(email, password, **extra_fields)

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)
    

class Staff(AbstractUser):
    first_name = models.CharField( max_length=100, blank=False)
    last_name = models.CharField( max_length=100, blank=False)
    nid = models.IntegerField(null=True)
    phone_number = models.CharField(max_length=20, unique=True)
    email = models.EmailField(max_length=254, unique=True, blank=False)
    username = models.CharField(max_length=50, blank=True, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.PROTECT, blank=True, null=True)
    email_confirmed = models.BooleanField(default=False)
    profile_photo = models.ImageField(upload_to="profile_photo/",blank=True, null=True)
    dob = models.DateField(default="1990-01-01", blank=True)
    address = models.TextField()
    city = models.CharField(max_length=100, blank=True)
    post_code = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=100, blank=True)
    employer = models.CharField(max_length=100, blank=True, null=True)
    MARTIAL_CHOICE = (
        ('single','Single'),
        ('married', 'Married'),
        ('devorce', 'Devorce'),
        ('other', 'Other'),
    )
    martial_status = models.CharField(choices=MARTIAL_CHOICE, max_length=10, default='single')
    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'phone_number']

    class Meta:
        verbose_name = ("Staff")
        verbose_name_plural = ("Staffs")

    def validate_staff_email(self, email=''):
        staff = Staff.objects.get(email=email)
        if staff:
            raise ValidationError(_('%(email)s is exist'), params={'email':email})
    
    def get_short_name(self):
        return self.last_name

staff/forms.py
from django import forms
from staff.models import Staff

class CreateStaffForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs.update({'class':'form-control'})
        self.fields['last_name'].widget.attrs.update({'class':'form-control'})
        self.fields['email'].widget.attrs.update({'class':'form-control'})
        self.fields['phone_number'].widget.attrs.update({'class':'form-control'})
        self.fields['nid'].widget.attrs.update({'class':'form-control'})
        self.fields['branch'].widget.attrs.update({'class':'form-control'})
    
    class Meta:
        model = Staff
        fields = ("first_name","last_name","email","phone_number","nid","branch")

class UpdateStaffForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['first_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['last_name'].widget.attrs.update({'class': 'form-control'})
        self.fields['email'].widget.attrs.update({'class': 'form-control'})
        self.fields['phone_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['nid'].widget.attrs.update({'class': 'form-control'})
        self.fields['branch'].widget.attrs.update({'class': 'form-control'})

    class Meta:
        model = Staff
        fields = ['first_name', 'last_name', 'email', 'phone_number', 'nid', 'branch', 'is_active', 'is_staff', 'is_superuser']

class ChangeBranchForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['branch'].widget.attrs.update({'class': 'form-control'})
    
    class Meta:
        model = Staff
        fields = ("branch",)

staff/views.py
from django.shortcuts import render,redirect,get_object_or_404
from staff.models import Staff
from staff.utils import get_all_permission, selected_perms
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.views.generic import FormView, TemplateView, ListView, UpdateView, DeleteView, DetailView
from django.contrib.auth.models import Permission
from django.contrib import messages
from staff.forms import CreateStaffForm, UpdateStaffForm, ChangeBranchForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
# Create your views here.


class HomeView(PermissionRequiredMixin, TemplateView):
    template_name = "staff/staff_home.html"
    permission_required = ['staff.view_staff']
    permission_denied_message = 'You dont have permission to view staff'
    raise_exception = True
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["staffs"] = Staff.objects.all().order_by('-pk')
        return context
    
class ChangeBranch(PermissionRequiredMixin, FormView):
    permission_required = ['staff.change_staff']
    permission_denied_message = 'You dont have permission to change staff'
    raise_exception = True
    template_name = 'staff/change_branch.html'
    form_class = ChangeBranchForm

    def post(self, request, *args, **kwargs):
        staff = get_object_or_404(Staff, pk=self.kwargs['pk'])
        form = self.form_class(data=request.POST, instance=staff)
        if form.is_valid():
            form.save()
            messages.success(request, 'Branch is updated successfully', extra_tags='alert alert-success')
        return redirect('staff:update_staff', pk=staff.pk)



class SetPermissions(PermissionRequiredMixin, FormView):
    template_name = "staff/set_permissions.html"
    perm_list = get_all_permission()

    def has_permission(self):
        #only allow superuser to access this view
        if self.request.user.is_superuser:
            return True
        else:
            return False
    def get(self, request, *args, **kwargs):
        staff = get_object_or_404(Staff, pk=self.kwargs['pk'])
        staff_perms_query = staff.user_permissions.all()
        staff_perms = [staff_perm.codename for staff_perm in staff_perms_query]

        context={
            'staff': staff,
            'staff_perms_query': staff_perms_query,
            'staff_perms': staff_perms,
            'perm_list': self.perm_list,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        staff = get_object_or_404(Staff, pk=self.kwargs['pk'])
        perms_selected = selected_perms(form_data=request.POST)
        staff_perms_query = staff.user_permissions.all()
        staff_perms = [staff_perm.codename for staff_perm in staff_perms_query]

        #remove existing perm that is not select
        for perm in staff_perms:
            if perm not in perms_selected:
                staff.user_permissions.remove(Permission.objects.get(codename=perm))
        
        #add selected perm
        for perm in perms_selected:
            if perm not in staff_perms:
                staff.user_permissions.add(Permission.objects.get(codename=perm))
        
        messages.success(request, f'success, updated permission for {staff.last_name}', extra_tags='alert alert-success')
        return redirect('staff:set_permission', pk=self.kwargs['pk'])

class CreateStaff(PermissionRequiredMixin, FormView):
    """Model definition for CreateStaff."""
    template_name = 'staff/create_staff.html'
    permission_required = ['staff.add_staff']
    permission_denied_message = 'You dont have permission to add staff'
    form_class = CreateStaffForm
    # TODO: Define fields here
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["staff"] = Staff.objects.all().order_by('-pk')[:10]
        context['form'] = self.form_class
        return context


    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            staff_obj = form.save(commit=False)
            #set default password
            staff_obj.set_password(raw_password=form.cleaned_data['phone_number'])
            staff_obj.save()
            messages.success(request, 'Successfully staff created', extra_tags='alert alert-success')
            return redirect('staff:staff_home')

class StaffUpdate(PermissionRequiredMixin, FormView):
    template_name = "staff/edit_staff.html"
    permission_required = ['staff.change_staff']
    permission_denied_message = 'You dont have permission to change staff'
    form_class = UpdateStaffForm
    password_form = PasswordChangeForm

    def post(self, request, *args, **kwargs):
        person = get_object_or_404(Staff, pk=self.kwargs['pk'])
        form = self.form_class(data=request.POST, instance=person)
        if form.is_valid():
            form.save()
            messages.success(request, "Staff Details Updated", extra_tags='alert alert-info')
            return redirect("staff:update_staff", pk=self.kwargs['pk'])
        else:
            context={
              'form' : self.form_class(data=request.POST, instance=person),
              'person' : person,
              'password_form' : self.password_form, 
            }
            messages.error(request, "Error Occoured", extra_tags="alert alert-danger")
            return render(request, self.template_name, context)

    def get(self, request, *args, **kwargs):
        person = get_object_or_404(Staff, pk=self.kwargs['pk'])
        password_form = self.password_form(user=person)
        password_form.fields['old_password'].widget.attrs.pop("autofocus",None)

        context={
              'form' : self.form_class(instance=person),
              'person' : person,
              'password_forms' : self.password_form, 
            }
        return render(request, self.template_name, context)


class DeleteStaff(PermissionRequiredMixin, DeleteView):
    permission_required = ['staff.delete_staff']
    permission_denied_message = "You Dont Have Permission to Delete Staff"
    raise_exception = True
    model = Staff
    template_name = 'staff/staff_confirm_delete.html'
    success_url = reverse_lazy('staff:staff_home')

class Login(FormView):
    form_class = AuthenticationForm
    template_name = 'staff/login.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)


        return redirect('staff:staff_home')

class Logout(LoginRequiredMixin, FormView):
    form_class = AuthenticationForm
    template_name = 'staff/login.html'
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('staff:login')

class StaffPageView(LoginRequiredMixin, TemplateView):
    template_name = "staff/staffpage.html"

class UpdatePassword(PermissionRequiredMixin, FormView):
    permission_denied_message = "You dont have permission to change staff"
    raise_exception = True
    form_class = PasswordChangeForm

    def has_permission(self):
        staff = get_object_or_404(Staff, pk=self.kwargs['pk'])
        if staff.pk == self.request.user.pk or self.request.user.is_superuser:
            return True
        else:
            return Flase

    def post(self, request, *args, **kwargs):
        staff = get_object_or_404(Staff, pk=self.kwargs['pk'])
        form = self.form_class(user=Staff, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Password is updated', extra_tags='alert alert-info')
        else:
            messages.error(request, 'Password is not updated', extra_tags='alert alert-danger')

        return redirect('staff:update_staff', pk=self.kwargs['pk'])

    

    
                

    

templates/staff/change_branch.html
{% extends 'dashboard/dashboard_base.html' %}
{% load crispy_forms_tags %}


{% block dashboard_content %}
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h4>Change Branch</h4>
            </div>
            <div class="card_body">
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success btn-block">Change Branch</button>
                </form>
            </div>
        </div>
    </div>
{% endblock dashboard_content %}
    

templates/staff/create_staff.html
{% extends 'dashboard/dashboard_base.html' %}
{% load crispy_forms_tags %}

{% block dashboard_content %}
{% include 'dashboard/message.html' %}
<div class="col-4">
    <div class="card">
        <div class="card-header">
            <h4>Add New Staff</h4>
        </div>
        <div class="card-body">
            <form action="{% url 'staff:create_staff' %}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <span class="text-muted">Phone number will be used as default password</span>
                <button type="submit" class="btn btn-info btn-block mt-2">Save</button>
            </form>

        </div>
    </div>

</div>
<div class="col-8">
    <div class="card">
        <div class="card-header">
            <h5 class="">10 Most Recent Staff</h5>
        </div>
        <div class="card-body">
            {% if staff|length > 0 %}
            <table class="table table-striped table-bordered table-hover table-condensed">
                <thead>
                    <th>#</th>
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                </thead>
                <tbody>
                    {% for person in staff %}
                    <tr>
                        <td>{{ forloop.counter }}.</td>
                        <td>
                            <a href=""> {{ person.get_full_name }}</a>
                        </td>
                        <td>{{ person.phone_number }}</td>
                        <td>{{ person.email }}</td>
                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <div class="alert alert-info">No staff have been added yet</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock dashboard_content %}

templates/staff/edit_staff.html
{% extends 'dashboard/dashboard_base.html' %}
{% load crispy_forms_tags %}
{% block dashboard_content %}
<div class="col-4">
    <div class="card">
        <div class="card-header">
            <h4>{{ person.get_full_name }}</h4>
        </div>
        <div class="card-body">
            <form action="{% url 'staff:update_staff' pk=person.pk%}" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary btn-blcok">Update</button>
            </form>
        </div>
    </div>
</div>
<div class="col-8">
    <div class="card">
        <div class="card-header">
            <h4>{{ person.get_full_name }}</h4>
        </div>
        <div class="card-body">
            <table class="table table-striped table-bordered table-hover table-condensed">
                <thead>

                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Date Joined</th>
                    <th>Branch</th>
                </thead>
                <tbody>
                    <tr>

                        <td>{{ person.get_full_name }}</td>
                        <td>{{ person.phone_number }}</td>
                        <td>{{ person.email }}</td>
                        <td>{{ person.date_joined|date:'d-m-Y H:i'}}</td>
                        <td>{{ person.branch }}</td>

                    </tr>

                </tbody>
            </table>

            {% if request.user.is_superuser %}
            <a href="{% url 'staff:set_permission' pk=person.pk %}" class="btn btn-outline-info">Set Permissions</a>
            <a href="{% url 'staff:change_branch' pk=person.pk %}" class="btn btn-outline-success">Change Branch</a>
            {% endif %}

        </div>
    </div>
</div>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h4>Update Password</h4>
        </div>
        <div class="card-body">
            <form action="{% url 'staff:update_password' pk=person.pk %}" method="post">
                {% csrf_token %}
                {{password_form|crispy}}
                <button type="submit" class="btn btn-primary btn-block">Update Password</button>
            </form>
        </div>
    </div>
</div>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h4>Profile Photo</h4>
        </div>
        <div class="card-body">
            
            <img class="card-img-top" src="{{ person.profile_photo.url }}" alt="" style="width: 200px; height: 200px;">
      
        </div>
    </div>
</div>
{% endblock dashboard_content %}

templates/staff/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% include 'dashboard/dashboard_stylesheet.html' %}
</head>
<body>
    <div class="loader"></div>
    <div id="app">
      <section class="section">
        <div class="container mt-5">
          <div class="row">
            <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
              <div class="card card-primary">
                <div class="card-header">
                  <h4>Login</h4>
                </div>
                <div class="card-body">
                  <form method="POST" action=" {% url 'staff:login' %}" class="needs-validation" novalidate="">
                      {% csrf_token %}
                    <div class="form-group">
                      <label for="email">Email</label>
                      <input id="email" type="email" class="form-control" name="username" tabindex="1" required autofocus>
                      <div class="invalid-feedback">
                        Please fill in your email
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="d-block">
                        <label for="password" class="control-label">Password</label>
                        <div class="float-right">
                          <a href="auth-forgot-password.html" class="text-small">
                            Forgot Password?
                          </a>
                        </div>
                      </div>
                      <input id="password" type="password" class="form-control" name="password" tabindex="2" required>
                      <div class="invalid-feedback">
                        please fill in your password
                      </div>
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox">
                        <input type="checkbox" name="remember" class="custom-control-input" tabindex="3" id="remember-me">
                        <label class="custom-control-label" for="remember-me">Remember Me</label>
                      </div>
                    </div>
                    <div class="form-group">
                      <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                        Login
                      </button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
    {% include 'dashboard/dashboard_script.html' %}
</body>
</html>

templates/staff/set_permissions.html
{% extends 'dashboard/dashboard_base.html' %}
{% load static %}

{% block dashboard_content %}
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h4>Set Permissions</h4>
            <button type="submit" class="btn btn-primary">Update Permissions</button>
            <a class="btn btn-primary btn-sm" href="{% url 'staff:create_staff' %}">
                <i class="fa fa-plus-circle"></i> Add New
            </a>
        </div>
        <div class="card-body p-0">
            <form method="post">
                {% csrf_token %}
                
                {% for perms in perm_list %}
                    
                    {% for key, value in perms.items %}
                    <fieldset class="form-group">
                        <legend class="col-form-label">{{key|capfirst}}roles</legend>
                        
                        {% for perm in value %}
                            <div class="form-check-inline">
                                <label for="" class="form-check-label">
                                    
                                    {% if perm.codename in staff_perms %}
                                        <input type="checkbox"  class="form-check-input" value="{{ perm.codename }}" name="{{ perm.codename }}" checked>
                                    {% else %}
                                        <input type="checkbox" class="form-check-input" value="{{ perm.codename }}" name="{{ perm.codename }}" id="">
                                    {% endif %}
                                    {{ perm.name }}
                                        
                                </label>
                            </div>
                        {% endfor %}
                            
                    </fieldset>
                    {% endfor %}
                        
                {% endfor %}
              <button type="submit" class="btn btn-outline-info btn-block">Update</button>      
            </form>
        </div>
    </div>
</div>
<div class="col-6">
    <div class="card">
        <div class="card-header">
            <h4>{{ staff.get_full_name }}'s Permissions</h4>
        </div>
        <div class="card-body">
            
            {% if staff_perms_query|length > 0 %}
                <ul>
                    
                    {% for staff_perm in staff_perms_query %}
                    <li>{{ staff_perm.content_type|capfirst }} : {{ staff_perm.name }}</li>
                    {% endfor %}
                        
                </ul>
            {% else %}
            <div class="alert alert-info">No permissions are set to {{ staff.last_name }}</div>
            {% endif %}
                
        </div>
    </div>
</div>
{% endblock dashboard_content %}
    

templates/staff/staff_confirm_delete.html
{% extends 'dashboard/dashboard_base.html' %}

{% block dashboard_content %}
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h4>Delete Staff</h4>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                <p>Are you Sure to Delete This {{ staff.get_full_name }}</p>
                <input type="submit" value="confirm" class="btn btn-warning btn-sm">
            </form>
        </div>
    </div>
</div>
    
{% endblock dashboard_content %}
    

templates/staff/staff_home.html
{% extends 'dashboard/dashboard_base.html' %}

{% block dashboard_content %}
<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h4>Staff</h4>
            <a class="btn btn-primary btn-sm" href="{% url 'staff:create_staff' %}">
                <i class="fa fa-plus-circle"></i> Add New
            </a>
        </div>
        <div class="card-body p-0">
            {% if staffs|length > 0 %}
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Phone</th>
                        <th scope="col">Email</th>
                        <th scope='col'>Branch</th>
                    </tr>
                </thead>
                <tbody>
                    {% for staff in staffs %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{staff.get_full_name}}</td>
                        <td>{{staff.phone_number}}</td>
                        <td>{{staff.email}}</td>
                        <td>{{staff.branch.name}}</td>
                        <td><a href="{% url 'staff:update_staff' pk=staff.pk %}" class="btn btn-primary btn-sm">Update</a></td>
                        <td><a href="{% url 'staff:delete_staff' pk=staff.pk %}" class='btn btn-danger btn-sm'>Delete</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <div class="alert alert-info">No staff have been added yet</div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock dashboard_content %}