branches/urls.py
from django.urls import path
from branches import views

app_name = 'branches'

urlpatterns = [
    path('', views.BranchHomeView.as_view(), name='branch_home'),
    path('create_branch/', views.CreateBranchView.as_view(), name='create_branch'),
    path('update_branch/<int:pk>/', views.UpdateBranchView.as_view(), name='update_branch'),
    path('delete_branch/<int:pk>/', views.DeleteBranchView.as_view(), name='delete_branch'),
]

dashboard/urls.py
from django.urls import path
from dashboard import views

app_name='dashboard'

urlpatterns = [
    path('', views.dashboard, name='dashboard')
]

pos_proj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('staff/', include('staff.urls')),
    path('supplier/', include('supplier.urls')),
    path('branch/', include('branches.urls')),
    path('products/', include('products.urls')),
    path('deliveries/', include('deliveries.urls')),
    path('customers/', include('customers.urls')),
    path('sales/', include('sales.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.ProductHomeView.as_view(), name='product_home'),
    path('create_product/', views.CreateProductView.as_view(), name='create_product'),
    path('product_detail/<int:pk>/', views.ProductDetailView.as_view(), name='detail_product'),
    path('update_product/<int:pk>/', views.ProductUpdateView.as_view(), name='update_product'),
    path('delete_product/<int:pk>/', views.ProductDeleteView.as_view(), name='delete_product'),
    path('add_transfer/', views.ProductAddTransfer.as_view(), name='add_transfer'),
    path('transfer_product/', views.TransferProduct.as_view(), name='transfer_product'),
    path('set_transfer_to/', views.SetTransferTO.as_view(), name='set_transfer_to'),
    path('delete_cart_product/<int:product_id>/', views.DeleteCartProduct.as_view(), name='delete_cart_product'),
    path('clear_list/', views.ClearList.as_view(), name='clear_list'),
]

sales/urls.py
from django.urls import path
from sales import views

app_name = 'sales'

urlpatterns = [
    
]

staff/urls.py
from django.urls import path
from staff import views
app_name='staff'

urlpatterns = [
    path('', views.HomeView.as_view(), name='staff_home'),
    path('set_permissions/<int:pk>/', views.SetPermissions.as_view(), name='set_permission'),
    path('change_branch/<int:pk>/', views.ChangeBranch.as_view(), name='change_branch'),
    path('create_staff/', views.CreateStaff.as_view(), name='create_staff'),
    path('update_staff/<int:pk>', views.StaffUpdate.as_view(), name='update_staff'),
    path('delete_staff/<int:pk>', views.DeleteStaff.as_view(), name='delete_staff'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('update_password/<int:pk>', views.UpdatePassword.as_view(), name='update_password'),
    path('staffpage/', views.StaffPageView.as_view(), name='staffpage'),
]

supplier/urls.py
from django.urls import path
from supplier import views
app_name = 'supplier'

urlpatterns = [
    path('', views.SupplierHomeView.as_view(), name='supplier_home'),
    path('create_supplier/', views.CreateSupplierView.as_view(), name='create_supplier'),
    path('update_supplier/<int:pk>/', views.UpdateSupplierView.as_view(), name='update_supplier'),
    path('delete_supplier/<int:pk>/', views.DeleteSupplierView.as_view(), name='delete_supplier'),
    path('detail_supplier/<int:pk>/', views.DetailSupplierView.as_view(), name='detail_supplier'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.

@login_required
def dashboard(request):
    return render(request, 'dashboard/dashboard.html')

templates/dashboard/dashboard_footer.html
<footer class="main-footer">
    <div class="footer-left">
      <a href="templateshub.net">Templateshub</a></a>
    </div>
    <div class="footer-right">
    </div>
  </footer>

templates/dashboard/dashboard_nav.html
<div class="navbar-bg"></div>
      <nav class="navbar navbar-expand-lg main-navbar sticky">
        <div class="form-inline mr-auto">
          <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg
									collapse-btn"> <i data-feather="align-justify"></i></a></li>
            <li><a href="#" class="nav-link nav-link-lg fullscreen-btn">
                <i data-feather="maximize"></i>
              </a></li>
            <li>
              <form class="form-inline mr-auto">
                <div class="search-element">
                  <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="200">
                  <button class="btn" type="submit">
                    <i class="fas fa-search"></i>
                  </button>
                </div>
              </form>
            </li>
          </ul>
        </div>
        <ul class="navbar-nav navbar-right">
          <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown"
              class="nav-link nav-link-lg message-toggle"><i data-feather="mail"></i>
              <span class="badge headerBadge1">
                6 </span> </a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right pullDown">
              <div class="dropdown-header">
                Messages
                <div class="float-right">
                  <a href="#">Mark All As Read</a>
                </div>
              </div>
              <div class="dropdown-list-content dropdown-list-message">
                <a href="#" class="dropdown-item"> <span class="dropdown-item-avatar
											text-white"> <img alt="image" src="assets/img/users/user-1.png" class="rounded-circle">
                  </span> <span class="dropdown-item-desc"> <span class="message-user">John
                      Deo</span>
                    <span class="time messege-text">Please check your mail !!</span>
                    <span class="time">2 Min Ago</span>
                  </span>
                </a> <a href="#" class="dropdown-item"> <span class="dropdown-item-avatar text-white">
                    <img alt="image" src="assets/img/users/user-2.png" class="rounded-circle">
                  </span> <span class="dropdown-item-desc"> <span class="message-user">Sarah
                      Smith</span> <span class="time messege-text">Request for leave
                      application</span>
                    <span class="time">5 Min Ago</span>
                  </span>
                </a> <a href="#" class="dropdown-item"> <span class="dropdown-item-avatar text-white">
                    <img alt="image" src="assets/img/users/user-5.png" class="rounded-circle">
                  </span> <span class="dropdown-item-desc"> <span class="message-user">Jacob
                      Ryan</span> <span class="time messege-text">Your payment invoice is
                      generated.</span> <span class="time">12 Min Ago</span>
                  </span>
                </a> <a href="#" class="dropdown-item"> <span class="dropdown-item-avatar text-white">
                    <img alt="image" src="assets/img/users/user-4.png" class="rounded-circle">
                  </span> <span class="dropdown-item-desc"> <span class="message-user">Lina
                      Smith</span> <span class="time messege-text">hii John, I have upload
                      doc
                      related to task.</span> <span class="time">30
                      Min Ago</span>
                  </span>
                </a> <a href="#" class="dropdown-item"> <span class="dropdown-item-avatar text-white">
                    <img alt="image" src="assets/img/users/user-3.png" class="rounded-circle">
                  </span> <span class="dropdown-item-desc"> <span class="message-user">Jalpa
                      Joshi</span> <span class="time messege-text">Please do as specify.
                      Let me
                      know if you have any query.</span> <span class="time">1
                      Days Ago</span>
                  </span>
                </a> <a href="#" class="dropdown-item"> <span class="dropdown-item-avatar text-white">
                    <img alt="image" src="assets/img/users/user-2.png" class="rounded-circle">
                  </span> <span class="dropdown-item-desc"> <span class="message-user">Sarah
                      Smith</span> <span class="time messege-text">Client Requirements</span>
                    <span class="time">2 Days Ago</span>
                  </span>
                </a>
              </div>
              <div class="dropdown-footer text-center">
                <a href="#">View All <i class="fas fa-chevron-right"></i></a>
              </div>
            </div>
          </li>
          <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown"
              class="nav-link notification-toggle nav-link-lg"><i data-feather="bell" class="bell"></i>
            </a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right pullDown">
              <div class="dropdown-header">
                Notifications
                <div class="float-right">
                  <a href="#">Mark All As Read</a>
                </div>
              </div>
              <div class="dropdown-list-content dropdown-list-icons">
                <a href="#" class="dropdown-item dropdown-item-unread"> <span
                    class="dropdown-item-icon bg-primary text-white"> <i class="fas
												fa-code"></i>
                  </span> <span class="dropdown-item-desc"> Template update is
                    available now! <span class="time">2 Min
                      Ago</span>
                  </span>
                </a> <a href="#" class="dropdown-item"> <span class="dropdown-item-icon bg-info text-white"> <i class="far
												fa-user"></i>
                  </span> <span class="dropdown-item-desc"> <b>You</b> and <b>Dedik
                      Sugiharto</b> are now friends <span class="time">10 Hours
                      Ago</span>
                  </span>
                </a> <a href="#" class="dropdown-item"> <span class="dropdown-item-icon bg-success text-white"> <i
                      class="fas
												fa-check"></i>
                  </span> <span class="dropdown-item-desc"> <b>Kusnaedi</b> has
                    moved task <b>Fix bug header</b> to <b>Done</b> <span class="time">12
                      Hours
                      Ago</span>
                  </span>
                </a> <a href="#" class="dropdown-item"> <span class="dropdown-item-icon bg-danger text-white"> <i
                      class="fas fa-exclamation-triangle"></i>
                  </span> <span class="dropdown-item-desc"> Low disk space. Let's
                    clean it! <span class="time">17 Hours Ago</span>
                  </span>
                </a> <a href="#" class="dropdown-item"> <span class="dropdown-item-icon bg-info text-white"> <i class="fas
												fa-bell"></i>
                  </span> <span class="dropdown-item-desc"> Welcome to Otika
                    template! <span class="time">Yesterday</span>
                  </span>
                </a>
              </div>
              <div class="dropdown-footer text-center">
                <a href="#">View All <i class="fas fa-chevron-right"></i></a>
              </div>
            </div>
          </li>
          
          {% if request.user.is_authenticated %}
          <li class="dropdown"><a href="#" data-toggle="dropdown"
            class="nav-link dropdown-toggle nav-link-lg nav-link-user"> <img alt="image" src="assets/img/user.png"
              class="user-img-radious-style"> <span class="d-sm-none d-lg-inline-block"></span></a>
          <div class="dropdown-menu dropdown-menu-right pullDown">
            <div class="dropdown-title">Hello {{ request.user.get_full_name }}</div>
            <a href="profile.html" class="dropdown-item has-icon"> <i class="far
                  fa-user"></i> Profile
            </a> <a href="timeline.html" class="dropdown-item has-icon"> <i class="fas fa-bolt"></i>
              Activities
            </a> <a href="#" class="dropdown-item has-icon"> <i class="fas fa-cog"></i>
              Settings
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'staff:logout' %}" class="dropdown-item has-icon text-danger"> <i class="fas fa-sign-out-alt"></i>
              Logout
            </a>
          </div>
          {% endif %}
            
          
          </li>
        </ul>
      </nav>

templates/dashboard/dashboard_script.html
{% load static %}
 <!-- General JS Scripts -->
 <script src="{% static 'dashboard/js/app.min.js' %}"></script>
 <!-- JS Libraies -->
 <script src="{% static 'dashboard/bundles/apexcharts/apexcharts.min.js' %}"></script>
 <!-- Page Specific JS File -->
 <script src="{% static 'dashboard/js/page/index.js' %}"></script>
 <!-- Template JS File -->
 <script src="{% static 'dashboard/js/scripts.js' %}"></script>
 <!-- Custom JS File -->
 <script src="{% static 'dashboard/js/custom.js' %}"></script>

templates/dashboard/dashboard_sidebar.html
<div class="main-sidebar sidebar-style-2">
  <aside id="sidebar-wrapper">
    <div class="sidebar-brand">
      <a href="index.html"> <img alt="image" src="assets/img/logo.png" class="header-logo" /> <span
          class="logo-name">Otika</span>
      </a>
    </div>
    <ul class="sidebar-menu">
      <li class="menu-header">Main</li>
      <li class="dropdown active">
        <a href="index.html" class="nav-link"><i data-feather="monitor"></i><span>Dashboard</span></a>
      </li>
      <li class="dropdown">
        <a href="{% url 'staff:staff_home' %}" class="menu-toggle nav-link has-dropdown"><i
            data-feather="briefcase"></i><span>Staff</span></a>
        
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="{% url 'staff:staff_home' %}">All Staff</a></li>
          <li><a class="nav-link" href="{% url 'staff:create_staff' %}">Add Staff</a></li>

        </ul>
      

      </li>
      <li class="dropdown">
        <a href="{% url 'supplier:supplier_home' %}" class="menu-toggle nav-link has-dropdown"><i
            data-feather="briefcase"></i><span>Supplier</span></a>
        
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="{% url 'supplier:supplier_home' %}">All Supplier</a></li>
          <li><a class="nav-link" href="{% url 'supplier:create_supplier' %}">Add Suppler</a></li>

        </ul>
      </li>
        <li class="dropdown">
          <a href="" class="menu-toggle nav-link has-dropdown"><i
              data-feather="briefcase"></i><span>Branch</span></a>
          
          <ul class="dropdown-menu">
            <li><a class="nav-link" href="{% url 'branches:branch_home' %}">All Branch</a></li>
            <li><a class="nav-link" href="{% url 'branches:create_branch' %}">Add Branch</a></li>
  
          </ul>
      

      </li>
      <li class="dropdown">
        <a href="" class="menu-toggle nav-link has-dropdown"><i
            data-feather="briefcase"></i><span>Products</span></a>
        
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="{% url 'products:product_home' %}">All Product</a></li>
          <li><a class="nav-link" href="{% url 'products:create_product' %}">Add Product</a></li>
          <li><a class="nav-link" href="{% url 'products:add_transfer' %}">Add Product Transfer</a></li>

        </ul>
    

    </li>
    <li class="dropdown">
      <a href="" class="menu-toggle nav-link has-dropdown"><i
          data-feather="briefcase"></i><span>Customer</span></a>
      
      <ul class="dropdown-menu">
        <li><a class="nav-link" href="{% url 'customers:customer_home' %}">All Customer</a></li>
        <li><a class="nav-link" href="{% url 'customers:create_customer' %}">Add Customer</a></li>
        

      </ul>
  

  </li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="briefcase"></i><span>Widgets</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="widget-chart.html">Chart Widgets</a></li>
          <li><a class="nav-link" href="widget-data.html">Data Widgets</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="command"></i><span>Apps</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="chat.html">Chat</a></li>
          <li><a class="nav-link" href="portfolio.html">Portfolio</a></li>
          <li><a class="nav-link" href="blog.html">Blog</a></li>
          <li><a class="nav-link" href="calendar.html">Calendar</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="mail"></i><span>Email</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="email-inbox.html">Inbox</a></li>
          <li><a class="nav-link" href="email-compose.html">Compose</a></li>
          <li><a class="nav-link" href="email-read.html">read</a></li>
        </ul>
      </li>
      <li class="menu-header">UI Elements</li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="copy"></i><span>Basic
            Components</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="alert.html">Alert</a></li>
          <li><a class="nav-link" href="badge.html">Badge</a></li>
          <li><a class="nav-link" href="breadcrumb.html">Breadcrumb</a></li>
          <li><a class="nav-link" href="buttons.html">Buttons</a></li>
          <li><a class="nav-link" href="collapse.html">Collapse</a></li>
          <li><a class="nav-link" href="dropdown.html">Dropdown</a></li>
          <li><a class="nav-link" href="checkbox-and-radio.html">Checkbox &amp; Radios</a></li>
          <li><a class="nav-link" href="list-group.html">List Group</a></li>
          <li><a class="nav-link" href="media-object.html">Media Object</a></li>
          <li><a class="nav-link" href="navbar.html">Navbar</a></li>
          <li><a class="nav-link" href="pagination.html">Pagination</a></li>
          <li><a class="nav-link" href="popover.html">Popover</a></li>
          <li><a class="nav-link" href="progress.html">Progress</a></li>
          <li><a class="nav-link" href="tooltip.html">Tooltip</a></li>
          <li><a class="nav-link" href="flags.html">Flag</a></li>
          <li><a class="nav-link" href="typography.html">Typography</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i
            data-feather="shopping-bag"></i><span>Advanced</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="avatar.html">Avatar</a></li>
          <li><a class="nav-link" href="card.html">Card</a></li>
          <li><a class="nav-link" href="modal.html">Modal</a></li>
          <li><a class="nav-link" href="sweet-alert.html">Sweet Alert</a></li>
          <li><a class="nav-link" href="toastr.html">Toastr</a></li>
          <li><a class="nav-link" href="empty-state.html">Empty State</a></li>
          <li><a class="nav-link" href="multiple-upload.html">Multiple Upload</a></li>
          <li><a class="nav-link" href="pricing.html">Pricing</a></li>
          <li><a class="nav-link" href="tabs.html">Tab</a></li>
        </ul>
      </li>
      <li><a class="nav-link" href="blank.html"><i data-feather="file"></i><span>Blank Page</span></a></li>
      <li class="menu-header">Otika</li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="layout"></i><span>Forms</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="basic-form.html">Basic Form</a></li>
          <li><a class="nav-link" href="forms-advanced-form.html">Advanced Form</a></li>
          <li><a class="nav-link" href="forms-editor.html">Editor</a></li>
          <li><a class="nav-link" href="forms-validation.html">Validation</a></li>
          <li><a class="nav-link" href="form-wizard.html">Form Wizard</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="grid"></i><span>Tables</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="basic-table.html">Basic Tables</a></li>
          <li><a class="nav-link" href="advance-table.html">Advanced Table</a></li>
          <li><a class="nav-link" href="datatables.html">Datatable</a></li>
          <li><a class="nav-link" href="export-table.html">Export Table</a></li>
          <li><a class="nav-link" href="editable-table.html">Editable Table</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="pie-chart"></i><span>Charts</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="chart-amchart.html">amChart</a></li>
          <li><a class="nav-link" href="chart-apexchart.html">apexchart</a></li>
          <li><a class="nav-link" href="chart-echart.html">eChart</a></li>
          <li><a class="nav-link" href="chart-chartjs.html">Chartjs</a></li>
          <li><a class="nav-link" href="chart-sparkline.html">Sparkline</a></li>
          <li><a class="nav-link" href="chart-morris.html">Morris</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="feather"></i><span>Icons</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="icon-font-awesome.html">Font Awesome</a></li>
          <li><a class="nav-link" href="icon-material.html">Material Design</a></li>
          <li><a class="nav-link" href="icon-ionicons.html">Ion Icons</a></li>
          <li><a class="nav-link" href="icon-feather.html">Feather Icons</a></li>
          <li><a class="nav-link" href="icon-weather-icon.html">Weather Icon</a></li>
        </ul>
      </li>
      <li class="menu-header">Media</li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="image"></i><span>Gallery</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="light-gallery.html">Light Gallery</a></li>
          <li><a href="gallery1.html">Gallery 2</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="flag"></i><span>Sliders</span></a>
        <ul class="dropdown-menu">
          <li><a href="carousel.html">Bootstrap Carousel.html</a></li>
          <li><a class="nav-link" href="owl-carousel.html">Owl Carousel</a></li>
        </ul>
      </li>
      <li><a class="nav-link" href="timeline.html"><i data-feather="sliders"></i><span>Timeline</span></a></li>
      <li class="menu-header">Maps</li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="map"></i><span>Google
            Maps</span></a>
        <ul class="dropdown-menu">
          <li><a href="gmaps-advanced-route.html">Advanced Route</a></li>
          <li><a href="gmaps-draggable-marker.html">Draggable Marker</a></li>
          <li><a href="gmaps-geocoding.html">Geocoding</a></li>
          <li><a href="gmaps-geolocation.html">Geolocation</a></li>
          <li><a href="gmaps-marker.html">Marker</a></li>
          <li><a href="gmaps-multiple-marker.html">Multiple Marker</a></li>
          <li><a href="gmaps-route.html">Route</a></li>
          <li><a href="gmaps-simple.html">Simple</a></li>
        </ul>
      </li>
      <li><a class="nav-link" href="vector-map.html"><i data-feather="map-pin"></i><span>Vector
            Map</span></a></li>
      <li class="menu-header">Pages</li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="user-check"></i><span>Auth</span></a>
        <ul class="dropdown-menu">
          <li><a href="auth-login.html">Login</a></li>
          <li><a href="auth-register.html">Register</a></li>
          <li><a href="auth-forgot-password.html">Forgot Password</a></li>
          <li><a href="auth-reset-password.html">Reset Password</a></li>
          <li><a href="subscribe.html">Subscribe</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i
            data-feather="alert-triangle"></i><span>Errors</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="errors-503.html">503</a></li>
          <li><a class="nav-link" href="errors-403.html">403</a></li>
          <li><a class="nav-link" href="errors-404.html">404</a></li>
          <li><a class="nav-link" href="errors-500.html">500</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i data-feather="anchor"></i><span>Other
            Pages</span></a>
        <ul class="dropdown-menu">
          <li><a class="nav-link" href="create-post.html">Create Post</a></li>
          <li><a class="nav-link" href="posts.html">Posts</a></li>
          <li><a class="nav-link" href="profile.html">Profile</a></li>
          <li><a class="nav-link" href="contact.html">Contact</a></li>
          <li><a class="nav-link" href="invoice.html">Invoice</a></li>
        </ul>
      </li>
      <li class="dropdown">
        <a href="#" class="menu-toggle nav-link has-dropdown"><i
            data-feather="chevrons-down"></i><span>Multilevel</span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Menu 1</a></li>
          <li class="dropdown">
            <a href="#" class="has-dropdown">Menu 2</a>
            <ul class="dropdown-menu">
              <li><a href="#">Child Menu 1</a></li>
              <li class="dropdown">
                <a href="#" class="has-dropdown">Child Menu 2</a>
                <ul class="dropdown-menu">
                  <li><a href="#">Child Menu 1</a></li>
                  <li><a href="#">Child Menu 2</a></li>
                </ul>
              </li>
              <li><a href="#"> Child Menu 3</a></li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
  </aside>
</div>

templates/dashboard/dashboard_stylesheet.html
{% load static %}
<!-- General CSS Files -->
<link rel="stylesheet" href="{% static 'dashboard/css/app.min.css' %}">
<!-- Template CSS -->
<link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
<link rel="stylesheet" href="{% static 'dashboard/css/components.css' %}">
<!-- Custom style CSS -->
<link rel="stylesheet" href="{% static 'dashboard/css/custom.css' %}">

templates/dashboard/message.html
{% if messages %}
    {% for message in messages %}
    <div class="col-12">
        <div {% if message.tags %} class="{{ message.tags }} alert-dismissible" id="" role="alert" {% endif %}>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"> &times; </span></button>
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} {% endif %}
                {{ message }}
            </div>
    </div>
    {% endfor %}
{% endif %}